USE social_buzz;

CREATE TABLE User (
  ID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  Age INT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE Profile (
  ID INT NOT NULL AUTO_INCREMENT,
  User_ID INT NOT NULL,
  Interests VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (User_ID) REFERENCES User(ID)
);

CREATE TABLE Location (
  ID INT NOT NULL AUTO_INCREMENT,
  User_ID INT NOT NULL,
  Address VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (User_ID) REFERENCES User(ID)
);

CREATE TABLE Session (
  ID INT NOT NULL AUTO_INCREMENT,
  User_ID INT NOT NULL,
  Device VARCHAR(255) NOT NULL,
  Duration INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (User_ID) REFERENCES User(ID)
);

CREATE TABLE Content (
  ID INT NOT NULL AUTO_INCREMENT,
  User_ID INT NOT NULL,
  Type VARCHAR(255) NOT NULL,
  Category VARCHAR(255) NOT NULL,
  URL VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (User_ID) REFERENCES User(ID)
);

CREATE TABLE ReactionTypes (
  Type VARCHAR(255) NOT NULL,
  Sentiment VARCHAR(255) NOT NULL,
  Score INT NOT NULL,
  PRIMARY KEY (Type)
);

CREATE TABLE Reaction (
  ID INT NOT NULL AUTO_INCREMENT,
  Content_ID INT NOT NULL,
  User_ID INT NOT NULL,
  Type VARCHAR(255) NOT NULL,
  Datetime DATETIME NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (Content_ID) REFERENCES Content(ID),
  FOREIGN KEY (User_ID) REFERENCES User(ID),
  FOREIGN KEY (Type) REFERENCES ReactionTypes(Type)
);


